Fixed Bug with fetching TDS version
I am using the long version number for tds, though the urls use the
short number to get the distribution.  So in the urls I do some sed
kungfu to shorten the version to the 2 or 3 digit value that is used
by the distribution servers.

-----------------------------------------------------------------------------
Luca posted this error to me in an email:
-----------------------------------------------------------------------------
Checking for thredds (tds) 4.2.20100908.2246
Sorry, the detected version of thredds [4.1.20100520.1554] is older than required minimum version [4.2.20100908.2246]

*******************************
Setting up Thredds Data Server... v4.2.20100908.2246
*******************************

Detected an existing thredds installation...
Do you want to continue with thredds installation and setup? [y/N] y

-rw-r--r-- 1 root root 23791469 May 24  2010 thredds.war
removed `thredds.war'
 Hmmm... Could not find local file thredds.war
--2010-12-13 13:34:51--  http://198.128.245.140/dist/thredds/4.2.20100908.2246/thredds.war
Connecting to 198.128.245.140:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2010-12-13 13:34:51 ERROR 404: Not Found.

 ERROR: Problem pulling down [thredds.war] from esg distribution site
 ERROR: Could not download http://198.128.245.140/dist/thredds/4.2.20100908.2246/thredds.war either
/usr/local/bin

Sorry...
This action did not complete successfully
Please re-run this task until successful before continuing further
-----------------------------------------------------------------------------