no using certificates-esg as the myproxy X509_CERT_DIR directory but explicitly using default
There is a lot of problems and issues and such dealing with this pesky
X509_CERT_DIR.  I am almost at the point where I am not going to set
it at all, which I think is best.  But on the way to getting there I
am just going to set it but use the default value explicitly.

I keep getting problems like this:

----------------------------
Publication test...
----------------------------

Enter your myproxy username: rootAdmin
ls: /home/esg-user/.globus/certificates-esg: No such file or directory
rmdir: /home/esg-user/.globus/certificates-esg: No such file or directory
X509_CERT_DIR = /home/esg-user/.globus/certificates-esg
/usr/local/globus/bin/myproxy-logon -s pcmdi3.llnl.gov -l rootAdmin -p 2119 -o /home/esg-user/.globus/certificate-file -T
Bootstrapping MyProxy server root of trust.
Error authenticating: GSS Major Status: Authentication Failed
GSS Minor Status Error Chain:
globus_gss_assist: Error during context initialization
globus_gsi_gssapi: Unable to verify remote side's credentials
globus_gsi_gssapi: Unable to verify remote side's credentials: Couldn't verify the remote certificate
OpenSSL Error: s3_pkt.c:1053: in library: SSL routines, function SSL3_READ_BYTES: sslv3 alert bad certificate SSL alert number 42

 ERROR: MyProxy not setup properly.  Unable to execute command.

Which according to those more knowledgeable than I about these things
is rooted in the X509_CERT_DIR not being properly set?