Make sure ${tomcat_install_dir}/work/Catalina dir exists...
Apparently the reason for the infamous error:

org.apache.jasper.JasperException: java.lang.IllegalStateException: No output folder
	org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:538)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:364)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:313)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:260)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:717)

...

is due to the ${tomcat_install_dir}/work/Catalina directory not being
present.  So now everytime just prior to tomcat starting up we make
sure the directory is there and that the ownership is set recursively
from "work".

(good looking out Luca - though the work dir gets created by tomcat
automatically.. let's see if this does it... I hope so)